---
apiVersion: v1
kind: Pod
metadata:
  name: kiptools
spec:
  restartPolicy: "Always"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  - name: composer-card-store
    persistentVolumeClaim:
      claimName: composer-pvc
  containers:
  - name: kiptools
    image: ibmblockchain/fabric-tools:1.1.0
    imagePullPolicy: Always
    command:
      - sleep
      - "43200"
    volumeMounts:
    - mountPath: /shared
      name: shared
    - mountPath: /home/composer/.composer
      name: composer-card-store
    env:
    - name: ORDERER_URL
      value: blockchain-orderer:31010
    - name: CHANNEL_NAME
      value: channel1
    - name: FABRIC_CFG_PATH
      value: /shared
    - name: GODEBUG
      value: "netdns=go"

